---
format: pdf
params:
  df_report: NA
  df_site: NA
  org_name: ""
  year: NA
title: "`r params$year` Water Quality Report"
---

```{r}
#| echo: false

library(knitr)
library(kableExtra)
suppressMessages(library(dplyr))
```

```{r}
#| label: tbl-sites
#| tbl-cap: Site Metadata
#| echo: false

dat <- data.frame(params$df_site, check.names = FALSE)

if (nrow(dat) > 0) {
  col_width <- trunc(40 / ncol(dat))
  col_width <- paste0(col_width, "em")

  knitr::kable(
    dat, "latex",
    longtable = TRUE,
    booktabs = TRUE,
    caption = "Site Metadata"
  ) |>
    kableExtra::kable_styling(
      latex_options = c("repeat_header", "striped")
    ) |>
    kableExtra::column_spec(seq_len(ncol(dat)), width = col_width) |>
    kableExtra::row_spec(0, bold = TRUE)
}
```

```{r}
#| echo: false
#| output: asis

# Drop extra rows
dat <- data.frame(params$df_report, check.names = FALSE)
param_list <- unique(dat$Parameter)

# Create kable
for (param in param_list) {
  df_mini <- dat |>
    filter(.data$Parameter %in% !!param) |>
    select(!"Parameter")

  bad_score <- which(df_mini$Score %in% c("Poor", "Does Not Meet Criteria"))

  tab <- df_mini |>
    knitr::kable(
      "latex",
      longtable = TRUE,
      booktabs = TRUE,
      caption = param
    ) |>
    kableExtra::kable_styling(
      latex_options = c("repeat_header", "striped")
    ) |>
    kableExtra::column_spec(1, width = col_width) |>
    kableExtra::row_spec(bad_score, color = "#850000")

  if ("Depth" %in% colnames(dat)) {
    tab <- tab |>
      kableExtra::column_spec(1, width = "20em") |>
      kableExtra::column_spec(2, width = "8em") |>
      kableExtra::column_spec(3, width = "12em")
  } else {
    tab <- tab |>
      kableExtra::column_spec(1, width = "28em") |>
      kableExtra::column_spec(2, width = "12em")
  }

  print(tab)
}
```
