#' Sidebar UI
#'
#' @description `mod_sidebar_ui()` produces the sidebar UI for the companion app
#' `wqdashboard`.
#'
#' @param id Namespace ID for module. Should match ID used by
#' `mod_sidebar_server()`.
#' @param varlist List of dropdown variables generated by `sidebar_var()`.
#'
#' @export
mod_sidebar_ui <- function(id, varlist) {
  ns <- NS(id)

  tagList(
    bslib::accordion(
      multiple = FALSE,
      # Select location ----
      bslib::accordion_panel(
        title = h2("1. Location"),
        value = "location",
        mod_sidebar_location_ui(ns("select_location"), varlist)
      ),
      # Select data ----
      bslib::accordion_panel(
        title = h2("2. Data"),
        value = "indicators",
        tabsetPanel(
          id = ns("tabset_param"),
          type = "hidden",
          tabPanelBody(
            "param_n",
            dropdown(
              ns("select_param_n"),
              label = h3("Select Indicator"),
              choices = varlist$param,
              multiple = FALSE
            )
          ),
          tabPanelBody(
            "param_score",
            dropdown(
              ns("select_param_score"),
              label = h3("Select Indicators"),
              choices = varlist$param_score
            )
          ),
          tabPanelBody(
            "param_download",
            dropdown(
              ns("select_param_download"),
              label = h3("Select Indicators"),
              choices = c(varlist$param, varlist$param_cat)
            )
          )
        ),
        tabsetPanel(
          id = ns("tabset_score"),
          type = "hidden",
          tabPanelBody(
            "show_score",
            checkboxInput(
              ns("chk_nascore"),
              label = "Include missing scores",
              value = TRUE
            )
          ),
          tabPanelBody("hide_score")
        ),
        tabsetPanel(
          id = ns("tabset_depth"),
          type = "hidden",
          tabPanelBody(
            "depth_n",
            dropdown(
              ns("select_depth_n"),
              label = h3("Select Depth"),
              choices = varlist$depth,
              sorted = FALSE,
              multiple = FALSE
            )
          ),
          tabPanelBody(
            "depth_all",
            dropdown(
              ns("select_depth_all"),
              label = h3("Select Depths"),
              choices = varlist$depth,
              sorted = FALSE
            )
          ),
          tabPanelBody("depth_null")
        )
      ),
      # Select date -----
      bslib::accordion_panel(
        title = h2("3. Date"),
        value = "dates",
        tabsetPanel(
          id = ns("tabset_dates"),
          type = "hidden",
          tabPanelBody(
            "year_n",
            dropdown(
              ns("select_year_n"),
              label = h3("Select Year"),
              choices = varlist$year,
              decreasing = TRUE,
              multiple = FALSE
            )
          ),
          tabPanelBody(
            "year_range",
            sliderInput(
              ns("select_year_range"),
              label = h3("Select Years"),
              min = min(varlist$year),
              max = max(varlist$year),
              value = c(
                min(varlist$year),
                max(varlist$year)
              ),
              sep = ""
            ),
            shinyWidgets::sliderTextInput(
              ns("select_month"),
              label = h3("Select Months"),
              choices = varlist$month,
              selected = c(
                varlist$month[1],
                varlist$month[length(varlist$month)]
              )
            )
          ),
          tabPanelBody(
            "year_all",
            dropdown(
              ns("select_year_all"),
              label = h3("Select Years"),
              choices = varlist$year,
              decreasing = TRUE,
              multiple = TRUE
            )
          )
        )
      )
    )
  )
}

#' Sidebar server
#'
#' @description `mod_sidebar_server()` produces the sidebar server for the
#' companion app `wqdashboard`.
#'
#' @param id Namespace ID for module. Should match ID used by
#' `mod_sidebar_ui()`.
#' @param df_sites Dataframe with site data. Must have been processed
#' by `format_sites()` and  include columns Site_ID, Site_Name.
#' @param df_data Dataframe with result data. Must have been processed
#' by `format_results()` and include columns Parameter, Month, Year.
#' @param df_score Dataframe with data scores. Must have been processed
#' by `score_results()` and include column Parameter.
#' @param selected_tab Reactive variable. Name of selected tab.
#' @param selected_site Reactive variable. Site_ID for site selected in
#' `mod_map_ui()`.
#'
#' @returns TO DO.
#'
#' @export
mod_sidebar_server <- function(
  id, df_sites, df_data, df_score, selected_tab, selected_site
) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    # Add modules ----
    loc_server <- mod_sidebar_location_server(
      "select_location",
      df_sites,
      selected_tab,
      selected_site
    )

    # Update tabs ----
    observe({
      if (selected_tab() == "map") {
        updateTabsetPanel(inputId = "tabset_param", selected = "param_n")
        updateTabsetPanel(inputId = "tabset_score", selected = "show_score")
        updateTabsetPanel(inputId = "tabset_dates", selected = "year_n")
      } else if (selected_tab() == "report_card") {
        updateTabsetPanel(inputId = "tabset_param", selected = "param_score")
        updateTabsetPanel(inputId = "tabset_score", selected = "hide_score")
        updateTabsetPanel(inputId = "tabset_dates", selected = "year_n")
      } else if (selected_tab() == "graphs") {
        updateTabsetPanel(inputId = "tabset_param", selected = "param_n")
        updateTabsetPanel(inputId = "tabset_score", selected = "hide_score")
        updateTabsetPanel(inputId = "tabset_dates", selected = "year_range")
      } else {
        updateTabsetPanel(inputId = "tabset_param", selected = "param_download")
        updateTabsetPanel(inputId = "tabset_score", selected = "hide_score")
        updateTabsetPanel(inputId = "tabset_dates", selected = "year_all")
      }
    }) |>
      bindEvent(selected_tab())

    observe({
      if (!"Depth" %in% colnames(df_data)) {
        updateTabsetPanel(inputId = "tabset_depth", selected = "depth_null")
      } else if (selected_tab() %in% c("map", "graphs")) {
        updateTabsetPanel(inputId = "tabset_depth", selected = "depth_n")
      } else {
        updateTabsetPanel(inputId = "tabset_depth", selected = "depth_all")
      }
    }) |>
      bindEvent(selected_tab())

    # Filter data ----
    df_score_filter <- reactive({
      req(input$select_year_n)

      dplyr::filter(df_score, .data$Year == input$select_year_n)
    })

    val <- reactiveValues(
      df_map = df_score[0, ],
      df_report = df_score[0, ]
    )

    # * Map data ----
    observe({
      req(selected_tab() == "map")
      req(input$select_param_n)
      req(df_score_filter())

      param <- input$select_param_n
      depth <- input$select_depth_n

      dat <- df_score_filter() |>
        dplyr::filter(
          .data$Parameter == !!param | is.na(.data$Parameter)
        )

      if (!input$chk_nascore) {
        dat <- dplyr::filter(dat, !is.na(.data$score_num))
      }

      chk <- isTruthy(depth) & !grepl("depth|height", tolower(param))
      if (chk) {
        dat <- dplyr::filter(dat, .data$Depth %in% !!depth)
      }

      val$df_map <- dat
    }) |>
      bindEvent(
        selected_tab(),
        df_score_filter(),
        input$chk_nascore,
        input$select_param_n,
        input$select_depth_n
      )

    # * Report data ----
    observe({
      req(selected_tab() == "report_card")
      req(df_score_filter())
      req(input$select_param_score)
      req(loc_server$sites_all())

      param <- input$select_param_score
      sites <- loc_server$sites_all()
      null_score <- c("No Data Available", "No Threshold Established")

      dat <- df_score_filter() |>
        dplyr::filter(
          .data$Parameter %in% !!param,
          .data$Site_ID %in% !!sites,
          !.data$score_str %in% !!null_score
        )

      if ("Depth" %in% colnames(dat)) {
        depth_list <- c(NA, input$select_depth_all)
        dat <- dplyr::filter(dat, .data$Depth %in% !!depth_list)
      }

      keep_col <- c(
        "Site_Name", "State", "Town", "Watershed", "Group", "Depth",
        "Parameter", "score_str"
      )

      val$df_report <- dplyr::select(dat, dplyr::any_of(keep_col))
    }) |>
      bindEvent(
        selected_tab(), df_score_filter(), input$select_param_score,
        loc_server$sites_all(), input$select_depth_all
      )

    # * Graph ----
    df_graph <- reactive({
      req(input$select_year_range)
      req(input$select_month)

      year_min <- input$select_year_range[1]
      year_max <- input$select_year_range[2]
      months <- sort_months(input$select_month)

      df_data |>
        dplyr::filter(
          .data$Year >= !!year_min,
          .data$Year <= !!year_max,
          .data$Month %in% !!months
        ) |>
        dplyr::select(!"Month")
    })

    # Return data ----
    return(
      list(
        sites_all = reactive({
          loc_server$sites_all()
        }),
        sites_n = reactive({
          loc_server$sites_n()
        }),
        site_list = reactive({
          loc_server$site_list()
        }),
        param_all = reactive({
          input$select_param_download
        }), # used for download
        param_n = reactive({
          input$select_param_n
        }), # used for map, graph
        depth_n = reactive({
          input$select_depth_n
        }),
        depth_all = reactive({
          input$select_depth_all
        }),
        year = reactive({
          input$select_year_n
        }),
        year_all = reactive({
          input$select_year_all
        }),
        df_map = reactive({
          val$df_map
        }),
        df_report = reactive({
          val$df_report
        }),
        df_graph = reactive({
          df_graph()
        })
      )
    )
  })
}
